### ISSUE TITLE
Allow relative tile placement when applying a map

### ISSUE THREAD

**Issue by ldunnplaymint** [playmint/ds#1014]
I want to be able to deploy a second map to my initial map deployment

**Comment by chrisfarms** [comment]
We now have two things to help with this situation:

* `ds offset` let's you generate a set of manifests offset from their position ... you can combine this with `ds apply -` to offset and apply a set of manifests
* the tile fabricator let's you more tiles around on the map using WASD, which can help you duplicate or shift map shapes around

many maps have logic that breaks once things are moved, so this problem is often more complicated that simply shifting the tiles and locations, so simply doing it directly with apply without some manual tweaking is likely not going to work.

closing as hopefully these existing solutions get us mostly there
