### ISSUE TITLE
As a team based experience maker I want to show which team each Unit is on so players can see whats going on

### ISSUE THREAD

**Issue by 5p0rt5BEArD** [playmint/ds#1023]
Would be useful for all open croissant games

Tonk Attack
Hexcraft
Ducks v Burger

**Comment by chrisfarms** [comment]
kick of with @Steedie and @PlaymintPaul ...

we considered: 

* floating labels 
* changing model color of units
* floating ducks n bucker models 

We decided allowing plugin code to change the model color of units (similar to how they can change tile colors) was the favourite direction.

So we will ...

* modify the MobileUnit unity component to support a color property
* have the frontend watch for plugin returned properties and set those colors

Out of scope:

* there will be no special system for ordering which plugin "wins" in setting a property (since many plugins can all be trying to set the same property) .... we will resolve any issues like this as plugin authors for now (ie change color of unit X if unit X is 10 tiles away from building)
* there will be no special handling of the "multiple units on one tile" clash for now ... if it's easy to detect this case and make it uncolored fine, but anything else is out of scope
