### ISSUE TITLE
Buildings should be able to create and equip bags

### ISSUE THREAD

**Issue by ldunnplaymint** [playmint/ds#116]
Add actions for:

CREATE_AND_EQUIP_BAG(buildingInstanceID, newBagId, equipSlot)
- like CRAFT this should only be valid when sent from a BuildingKind implementation
- results in a new bag equip at equipSlot on the building
- requires that equipslot is empty

TRANSFER_BAG(buildingInstanceID, fromEquipee, fromEquipSlot, toEquipee, toEquipSlot)
- allows a building to move where a bag is equip to
- like CRAFT this should only be valid when sent from a BuildingKind implementation
- requires that equipees are within range of each other ... and within range of buildingInstance

**Comment by chrisfarms** [comment]
I've been thinking recently that bag creation should possibly be exclusively a building action because:

* I think making it _too_ easy to create bags will just pollute the data with tons of empty bags everywhere
* I think it's conceptually quite nice making "bags" something that buildings are exclusively in control of
* we already need buildings to be able to create bags (for things like shops) - so it's simplier to just do it in one place with one rule

**Comment by chrisfarms** [comment]
completed in https://github.com/playmint/ds/pull/477
