### ISSUE TITLE
The create zone button price text doesn't populate if the user signs in via metamask

### ISSUE THREAD

**Issue by ldunnplaymint** [playmint/ds#1288]
Feels like a race condition. It does populate through localdevaccount.

**Comment by chrisfarms** [comment]
I think this is when metamask hasn't switched to the correct network.

we are not very agressive about forcing the switch (because it can cause annoying infinite loops) ... but maybe we need a network banner at the top of the page to indicate you need to switch networks, and we should not show the mint button if we detect you are on wrong network
