### ISSUE TITLE
extraction prediction is inaccurate

### ISSUE THREAD

**Issue by PlaymintDavid** [playmint/ds#1374]
https://github.com/playmint/ds/assets/129759334/d415a0f6-e630-4da4-a5a0-7bde9919ab44

I'd expect to receive 100 goo here, but I'm not.

**Comment by ldunnplaymint** [comment]
Looks like the progress bar out of sync

**Comment by ldunnplaymint** [comment]
@PlaymintDavid Is this against Redstone?

**Comment by PlaymintDavid** [comment]
Yes.

**Comment by chrisfarms** [comment]
hypothesis: this is because of a change I made to avoid fetching the latest block ... which means the progerss bar is 1 or 2 blocks out of sync with reality 

potential fixes:

*  offset the block time in extractor plugin by 2 (hacky, prob only 60% effective)
* pass in the non-simulated block number
