### ISSUE TITLE
It's possible to press the "Craft" button on a building before the pending input tx has finished

### ISSUE THREAD

**Issue by ldunnplaymint** [playmint/ds#236]
If the user fills all of the crafting slots in a building, they will notice that the craft button is lit before the last input has exited the pending state. 

Crafting in this state causes the input slot to get stuck in pending until the user does a reset.

**Comment by chrisfarms** [comment]
the button is correct, the pending state is incorrect.

this is an artifact of #79 and the fact that "pending" is a lie.

To resolve this we would either need to get #79 implemented or remove all the guess-based pending stuff and accept the lack of UI feedback until we are ready to implement it properly.

So I think this issue is probably just a duplicate of #79 or #93

**Comment by ldunnplaymint** [comment]
Duplicate
