### ISSUE TITLE
The building site should remember the type of building it is going to be

### ISSUE THREAD

**Issue by PlaymintPaul** [playmint/ds#344]
At the moment, if you click "Build" and click on a building site you have to select the correct building type to see the input materials.

**Comment by chrisfarms** [comment]
was discussing this with baker a while back ... we both agree ... but it will mean we basically need to split construction into START_CONSTRUCTION and END_CONSTRUCTION .... which actually goes well with the ideas of construction taking time so probably isn't the end of the world

**Comment by PlaymintDavid** [comment]
I don't follow. Are you saying it's not possible or not desirable to help a player find out what building type it's going to be?

**Comment by chrisfarms** [comment]
it's both possible and desirable.

but it requires changing how construction works a bit... since it's not just a client-side thing

we are planning to do this. and the end result will be that once construction has started, everyone will know what building it is going to be, and the constructor will not "lose" which building they are mid constructing

**Comment by PlaymintDavid** [comment]
Okay great :)

**Comment by chrisfarms** [comment]
@PlaymintDavid  You'll be happy to hear that it looks like I introduced a bug this sprint that requires this ticket resolved 😅.... so this just task just become high priority and will be sorted soon

@ldunnplaymint ... there's an issue where the building selection disappears during adding the construction materials ... rather than work around it, I'm bumping this as a high priority task to sort tomorrow

**Comment by ldunnplaymint** [comment]
Sounds good to me
