### ISSUE TITLE
Big goo extractor doesn't give me goo

### ISSUE THREAD

**Issue by PlaymintDavid** [playmint/ds#621]
I used all my goo to create a Big Goo Extractor only to find that it doesn't extract "Goo" but "Big Goo". It turns out I can't use Big Goo to create extractors, so that leaves me having spent all my Goo on something I didn't need.

This is counter-intuitive!

**Comment by ldunnplaymint** [comment]
I did exactly this...

**Comment by ldunnplaymint** [comment]
I think filtering by "Playmint", "Mine" or "Randomers" in some way would help. Because it appeared so early into the game and the obvious naming snafu, it sounded like it was a new Playmint building I hadn't seen.

I know we have plans for discoverability but atm, "I can build" and "I can't build" might be too wider pools of things.

**Comment by PlaymintDavid** [comment]
Agree that filtering or adding something to the filename would help.

**Comment by ldunnplaymint** [comment]
We need to implement proper filtering, potentially using itemKind as the solution.
