### ISSUE TITLE
Vault of knowledge buttons don't do anything

### ISSUE THREAD

**Issue by ldunnplaymint** [playmint/ds#755]
I know Paul knows this is true but I want a ticket because may forget otherwise

DOCS should link to the docs and create a building should link to the building docs (Or building builder if we get it done?)

**Comment by chrisfarms** [comment]
In https://github.com/playmint/ds/pull/812 I updated the the VaultOfKnowledge to show links that open in new window ... but didn't mark this is closed as I @PlaymintPaul should:

* make sure the text in the VaultOfKnowledge plugin makes sense and reads well (not just my example)
* remove the "open the xxx" tasks from quests, since you can't actually check if someone has visited the pages
