### ISSUE TITLE
World last reset at [date-time]

### ISSUE THREAD

**Issue by PlaymintDavid** [playmint/ds#89]
I explored the map then left the computer for an hour or two. When I came back I refreshed and it asked me to sign via metamask.

When the map reloaded the map was unexplored. I _think_ that's because the map was reset but I'm not 100% sure. As a suggestion, perhaps the game could start with "World last reset at [date-time]" in the log to avoid ambiguity?

**Comment by ldunnplaymint** [comment]
Currently, session keys are a per instance entity. We have identified a bit or work to make sessions keys persist between instances and intend on doing it. The asterisk is that a session key WILL expire at some point and you will need to resign.

**Comment by PlaymintDavid** [comment]
I'm not worried about the Metamask sign in. I just added that for information.

It was more that I was confused what had happened to the world and a 'world last reset at...' would have helped. Not a big deal though.

**Comment by chrisfarms** [comment]
this is harder to implement than it may seem and so might become a wontfix I'm affraid.

the non-persistent deployments can loose there state under a large number of conditions, it's not just something that occurs when we want it to. So we have no timestamp for a reset.

This is only a problem for our private testnet stuff tho, which are not intented for the general public anyway.... alpha will be on a public testnet and so will be a persistent environment, not one that gets wiped every time the wind blows in the wrong direction, so the experience for regular players should not be a jaring "ahhh the world disappeared!"

what we _should_ be doing for the private testnet deployment tho is: https://github.com/playmint/ds/issues/100
(which I think would go a long way to helping resolve this issue even on the non-persistent environments .... since the world might have been wiped, but at least you get shown the release notes, which has a kinda implication of what probably happended)
