### ISSUE TITLE
Always Active Plugins run with no instances

### ISSUE THREAD

**Issue by 5p0rt5BEArD** [playmint/ds#973]
Always active plugin code runs even if there are no instance of the building. Seems wrong.

**Comment by ldunnplaymint** [comment]
Possible solution is only running always active plugins if there is an instance on the map. We need to make sure we are happy with the performance implications of that.

**Comment by JackPlaymint** [comment]
This is only worthwhile doing if the plugin is no longer active after you've destroyed the final instance of the buildingkind. Currently this will cause an extra loop which isn't worth the performance hit.

**Comment by Steedie** [comment]
I made this change while working on plugin memory issues: https://github.com/playmint/ds/compare/main...performance-experiments#diff-70230fcb801e60eb7d9b0f16f6db3bee7c9c41d392d50fd13d643d2345086a30

So that it only loads plugins (to sandbox) that have an instance of it placed in the world. Filtering the unused plugins works to decrease the total memory being used, especially when there are a lot of plugins that aren't placed in the world, but I see what you're saying about the extra loop - wondering if the decrease in total memory used after this change might be worth the extra step.
